server:
  host: 0.0.0.0
  port: 9000


database:
  type: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  name: llmchat


vector:
  type: milvus
  use_gpu: True
  device: 0
  host: 127.0.0.1
  port: 19530
  user:
  password:


embedding:
  use_gpu: True
  device: 0
  name:


llm:
  url: http://10.133.95.100:9103/v1
  key: "<KEY>"
  model: gxllm
  max_tokens: 8192
  temperature: 0