server:
  host: 0.0.0.0
  port: 9000
  secret_key: secret_key


database:
  type: mysql
  host: 10.133.95.100
  port: 9104
  user: root
  password: root
  name: llmchat


vector:
  type: milvus
  use_gpu: True
  device: 0
  host: 10.133.95.100
  port: 9107
  user:
  password:


embedding:
  type: local
  use_gpu: True
  device: 0
  name: text2vec-base-chinese
  normalized: True


llm:
  url: http://10.133.95.100:9103/v1
  key: "<KEY>"
  model: gxllm
  max_tokens: 8192
  temperature: 0